version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

    volumes:
      - ./services/backend:/app
      - ./services/backend/src:/app/src

    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000


  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 5173:5173
