version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - ./services/backend:/app
  
    command: >
      bash -c "aerich upgrade && uvicorn src.main:app --reload --host 0.0.0.0 --port 5000"

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - './services/frontend/src:/app/src'
      - '/app/node_modules'
    ports:
      - 5173:5173