version: '3.8'
services: 

  # backend:
  #   build: ./services/backend
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres1!@srcbot1.c7okouiqu9jh.us-east-1.rds.amazonaws.com:5432/srcbot1
  #     - SECRET_KEY=09d25e094faa6caaaron8166b7a9563b93f79f6f0f4caa6cf63b88e8d3e7
  #     - IS_LOCAL=true
  #     - yacht_username=admin@draftwarroom.com
  #     - yacht_password=admin1
  #     - FRONTEND_URL=https://draftwarroom.com
  #     - TOKEN_SECRET_KEY=rlXGof--njwxngwHx6XveE0PEuxW0tmtgHZxnYXBMTE=
  #   volumes:
  #     - ./services/backend:/app
  #     - ./services/backend/src:/app/src

  #   #local development uvicorn - supports hot reloadng (on code changes the backend container will reflect the changes instant)
  #   command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
  #   #prod
  #   #command: gunicorn -k uvicorn.workers.UvicornWorker -t 1000 -b 0.0.0.0:5000 --log-level info --reload src.main:app

  # frontend:
  #   build: ./services/frontend
  #   environment:
  #    # - VITE_APP_BACKEND_URL=https://api.draftwarroom.com
  #     - VITE_APP_YAHOO_CLIENT_ID=dj0yJmk9NTZlWXZjdlY1SUZhJmQ9WVdrOVkxWnZjemRJVVhFbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTgz
  #   volumes:
  #     - './services/frontend:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 5173:5173
  #   command: npm run dev

  yahoo_bot:
    build:
      context: ./services/baseball_bot
    #restart: always
    environment:
      #Bot ID from the GroupMe developers page (REQUIRED IF USING GROUPME)
      BOT_ID: 29d18b385eb0307982d596c2da
      BOT_TYPE: GroupMe
      #ESPN league id (REQUIRED)
      LEAGUE_ID: 51838
      FEATURE_ENV_VARS: DAILY_WAIVERS,GET_LEAGUE_MATCHUPS
      BACKEND_URL: https://api.draftwarroom.com
      access_token:  KzYjCgeZ4xoW3WJ1Ue_nVGMgCLKCvTM95iajuoLkc8xvFNGqBHAP5Af.ExHPKqWFtWrstnCv8eiFi0lrIuyIVPvOWpadhvcMU3EIuQ5D1szMiGQCwUsy.qllKeSsYnBp6UDYwbUZzyvqLWRDhLfdQ4WJfU8Bl4Esy82aW_D0cx4Rm0aySzZUhpPpvoBD0zw5Em.N0dSraJ1hZ5FfK7rto0y4Svkeo2bLLhLnUyRgSTuf.HXQ6pEluW6SobEb9e4hwZQkfAWZrgLrBQ2MoaMW6cCsYKYllfVPtBqivLOs_kpunxQl8Xgur7rwYaTz24UgSmO.hZZU0R6BUcL8aBgdhswquJOUhn__iVCGlJhJzI4aSLfEdjWTphwHfHrfz0uJFhG7fNMOFY5sFhovur2LITThxh3sRHZYlnSfp_zCn7ueoiVIWkRhBIWBRDoEPYSEvowJxPTfrqWhLNmGGu1cSa4M1lc9XBz_ET9iur8wFVmmfQAtWzd7ZMbycLEoi9MxSn_9xOOAre26KuwRNnHPOL9QizUmPuSZHNKYNFPHSLcp8NQlHMQ7yTDy4DKFvMqfAe4LDe_7MjlVKeGFcovz4zWxK64qrHb4odztm4XQFKR0FRmlTm8yLjScYzHD53uQ7NI1fdFCkwAk45TsGGmafwFvo3o5D7MKfcD2rNIXZsMzc0BemLe0LRHKDTO3Tco7T5ZDKfsJz5P8WlOmMruLSi4JgelgZHU0wwAXdDqXtt8b7Bd2zH_7nl3h5oiR0HSMoIIPkhG_eEsCGOH4Efvk7vvkLFkr7ouqho58PLnKMRibSQlma1lDicyIKRx3kZv8_1Cx4VYYhJB9025sU.ChzwgHsF7lp058U33Gq9yBt4URNTnf4ZUf8wfaRBOdHijNXdYfuGHqjteQcY7qkalP3pCeEHllZCk-
      refresh_token: ALughGWBOfDVvzKpzpU9Sz01SD98~000~JrELwagUtMLxhMDCVUiyCOU-
      token_time: 3600
    image: yahoo_bot:2.8

# data = {
#     "bot_type": "GroupMe",
#     "bot_id": "1234567890",
#     "league_id": "51838",
#     "yahoo_private_key": "dj0yJmk9NTZlWXZjdlY1SUZhJmQ9WVdrOVkxWnZjemRJVVhFbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTgz",
#     "yahoo_private_secret": "e656aa67c44c49a1c201c4f984ef6b83fb09fe73",
#     "feature_flags": "DAILY_WAIVERS,GET_LEAGUE_MATCHUPS",
#     "backend_url": "https://api.draftwarroom.com",
#     "init_msg": "Bot starting..",
#     "access_token": "KzYjCgeZ4xoW3WJ1Ue_nVGMgCLKCvTM95iajuoLkc8xvFNGqBHAP5Af.ExHPKqWFtWrstnCv8eiFi0lrIuyIVPvOWpadhvcMU3EIuQ5D1szMiGQCwUsy.qllKeSsYnBp6UDYwbUZzyvqLWRDhLfdQ4WJfU8Bl4Esy82aW_D0cx4Rm0aySzZUhpPpvoBD0zw5Em.N0dSraJ1hZ5FfK7rto0y4Svkeo2bLLhLnUyRgSTuf.HXQ6pEluW6SobEb9e4hwZQkfAWZrgLrBQ2MoaMW6cCsYKYllfVPtBqivLOs_kpunxQl8Xgur7rwYaTz24UgSmO.hZZU0R6BUcL8aBgdhswquJOUhn__iVCGlJhJzI4aSLfEdjWTphwHfHrfz0uJFhG7fNMOFY5sFhovur2LITThxh3sRHZYlnSfp_zCn7ueoiVIWkRhBIWBRDoEPYSEvowJxPTfrqWhLNmGGu1cSa4M1lc9XBz_ET9iur8wFVmmfQAtWzd7ZMbycLEoi9MxSn_9xOOAre26KuwRNnHPOL9QizUmPuSZHNKYNFPHSLcp8NQlHMQ7yTDy4DKFvMqfAe4LDe_7MjlVKeGFcovz4zWxK64qrHb4odztm4XQFKR0FRmlTm8yLjScYzHD53uQ7NI1fdFCkwAk45TsGGmafwFvo3o5D7MKfcD2rNIXZsMzc0BemLe0LRHKDTO3Tco7T5ZDKfsJz5P8WlOmMruLSi4JgelgZHU0wwAXdDqXtt8b7Bd2zH_7nl3h5oiR0HSMoIIPkhG_eEsCGOH4Efvk7vvkLFkr7ouqho58PLnKMRibSQlma1lDicyIKRx3kZv8_1Cx4VYYhJB9025sU.ChzwgHsF7lp058U33Gq9yBt4URNTnf4ZUf8wfaRBOdHijNXdYfuGHqjteQcY7qkalP3pCeEHllZCk-",
#     "refresh_token": "ALughGWBOfDVvzKpzpU9Sz01SD98~000~JrELwagUtMLxhMDCVUiyCOU-",
#     "token_time": 3600
    
# }


# Build, tag and push docker image to docker hub:
#docker build -t aarondawg14/draftwarroom:2.8 ./services/baseball_bot
#docker tag aarondawg14/draftwarroom:2.1 aarondawg14/draftwarroom:latest
#docker push aarondawg14/draftwarroom:2.8
#docker push aarondawg14/draftwarroom:latest




#docker compose up -d --build

#29d18b385eb0307982d596c2da
#53047